name: ci backend

on:
  merge_group:
  pull_request:

jobs:

  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    strategy:
      matrix:
        go-version: [ '1.21', '1.22' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: "**/go.sum"

      - name: Test
        run: |
          go test -race -v ./...